import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#00522a",
        "outline": "#737783",
        "on-surface-variant": "#434752",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed": "#ffdea5",
        "on-primary-fixed": "#001944",
        "on-tertiary-container": "#e7bf75",
        "on-background": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "primary-container": "#174ea6",
        "secondary": "#236b40",
        "outline-variant": "#c3c6d4",
        "on-secondary-fixed": "#00210e",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#8ed7a1",
        "on-tertiary-fixed-variant": "#5d4201",
        "primary-fixed-dim": "#afc6ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#afc6ff",
        "on-primary-fixed-variant": "#004299",
        "tertiary-container": "#694d0c",
        "tertiary-fixed-dim": "#e9c176",
        "primary": "#003781",
        "on-tertiary-fixed": "#261900",
        "on-primary-container": "#adc5ff",
        "inverse-surface": "#2f3131",
        "surface-tint": "#2a5bb3",
        "secondary-fixed": "#a9f3bc",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary": "#4e3700",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f1",
        "surface": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#a6f0b9",
        "surface-container-low": "#f3f3f3",
        "primary-fixed": "#d9e2ff",
        "background": "#f9f9f9",
        "surface-dim": "#dadada",
        "on-secondary-container": "#286f44",
        "surface-container": "#eeeeee",
        "on-surface": "#1a1c1c",
        "on-tertiary": "#ffffff"
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
};
export default config;
